[build]
  command = "netlify/functions/server.js"       
  publish = "build"               
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200
  force = true


