[build]
  command = "npm run build"       # Update if you use yarn or a different build command
  publish = "build"               # Update this to your actual output folder (e.g., "dist", "out", or "public")
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200
  force = true
