[build]                   
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200
  force = true







